In [ ]:
#No umbral, activacion lineal, necesita valores normalizados, desvEst=1

In [ ]:
"""
queremos que descubra patrones, y por consiguiente, se van a it activando consecuenemente

_detector de distribucion, ponele_se activa si parece, sino no...

Hebb-> si neu presin contribuye a la activacion, se enriquece que alimente al modelo
* es el producto interno, el np.dot()
delta_w_i_j = eta**x_i*y_j

=> y_j = sum(x_i * w_i_j)

arancamos con una unid de salida y_j

N entradas, M salidas con N > M

w va a tender a orientarse ne la orientacion que maximiza la varianza

problemita... los pesos pueden crecer inifinitamente(caos en lso floatting points)
#emparchable, si le metemos reestricciones como norma = 1
#moentum de signo contrario, que alentiza el aprendizaje
las unidades terminan aprendinedo parecido, no sirve mucho si metemos datos nuevos con varianza

=> OJA!!!!

aprendiendo a prototipar algo, mejoremos correcciones aprovechando esto

correccion proporcional a la diff de estimulo entrada, y lo que creemos seria una buena entrada

=> delta_w_i_j = eta * (x - estimador_buena_entrada) * Y_j

con estimador_buena_entrada = y_j * w_i_j
#esto lo hace para CADA punto

#######momento!!!! y si quiero más salidas???? M ###########

otro OJA

deltaw_i_j = eta * (x - estimador_buena_entrada) * y_j

donde estimador_buena_entrada = sum(y_k * W_i_k) hasta M

o sea que corrijo con todos los pesos de cada salida, con cada x

concomitantemente esto implica que activo para cada salida, entonces obtengo ortogonal a la n-1 la dir de mayor varianza

o sea, que orienta los w en el mismo subespacio que las M componentes princioales, da el plano donde viven las componentes prinicpales

#si quisiera las componentes prinicpales???   qué hago???

adios oja, hola SANGER!!!!

delta_w_i_j = eta * (x - estimador_buena_entrada) * Y_j

con estimador_buena_entrada como estimador_buena_entrada = sum(y_k * w_i_k)  hasta J

dejado de lado la primer componentes ya obtenida
"""

'\nqueremos que descubra patrones, y por consiguiente, se van a it activando consecuenemente\n\n_detector de distribucion, ponele_se activa si parece, sino no...\n\nHebb-> si neu presin contribuye a la activacion, se enriquece que alimente al modelo\n* es el producto interno, el np.dot()\ndelta_w_i_j = eta**x_i*y_j\n\n=> y_j = sum(x_i * w_i_j)\n\narancamos con una unid de salida y_j\n\nN entradas, M salidas con N > M\n\nw va a tender a orientarse ne la orientacion que maximiza la varianza\n\nproblemita... los pesos pueden crecer inifinitamente(caos en lso floatting points)\n#emparchable, si le metemos reestricciones como norma = 1\n#moentum de signo contrario, que alentiza el aprendizaje\nlas unidades terminan aprendinedo parecido, no sirve mucho si metemos datos nuevos con varianza\n\n=> OJA!!!!\n\naprendiendo a prototipar algo, mejoremos correcciones aprovechando esto\n\ncorreccion proporcional a la diff de estimulo entrada, y lo que creemos seria una buena entrada\n\n=> delta_w_i_j 

In [ ]:
# con Q = 0 Hebb, Q = 1 OJA ,Q = M OJA extendido, con Q = j Sanger

##algoritmo para no supervisado

#P filas , N col de entrada
#salida M filas
#definir un eta

#esto anda
import numpy as np

def NoSuperv(dataset , M = int(4) , eta = 0.001 , q = 4):

    """
    M es el num de neuronas de salida
    """

    N = dataset.shape[1]

    w = np.zeros((N , M))
#aca solo genero los pesos
    for i in range(0 , w.shape[0]):

        for j in range(0 , w.shape[1]):

            w[i][j] = np.random.uniform(-0.1 , 0.1)

    delta_w = np.zeros((N , M))

    y = np.zeros((1,M))

    print(f'dataset_dim: {dataset.shape}')

    for h in range(0,dataset.shape[0]):#hasta P

        x = dataset[h:h+1 , :]

        print(f'x_dim: {x.shape}')

        y[:] = np.dot(x , w)

        print(f'y_dim: {y.shape}')

        for j in range(0,M):

            for i in range(0,N):

                estimador_buena_entrada = 0

                for k in range(0,int(q)):

                    print(f'dim_y_k: {y[0,k].shape} dim_w_i_k: {w[i,k].shape} el producto: {y[0,k]} * {w[[i,k]]}')

                    estimador_buena_entrada += (y[0,k] * w[i,k])#elijo creer que pude arreglar esto

                print(f"EBE: {estimador_buena_entrada} y_i_k: {y[0,j]} w_i_k: {delta_w[i,k]}")

                delta_w[i,j] = ((x[0,i] - estimador_buena_entrada) * y[0,j])#aparentemente se rompe aca

        w += eta * delta_w

    return(w)

In [ ]:
"""
ej1
a = [a1--6]

generar un hiper rectangulo

ej2

combinaciones lineales con tres matrices
"""

'\nej1\na = [a1--6]\n\ngenerar un hiper rectangulo\n\nej2\n\ncombinaciones lineales con tres matrices\n'

In [ ]:
#ejerciio 1
#A vect de naturales todos distintos
#X vector de np.random.uniform(A_i) entre -A_i y A_i

#entrenar modelos de 4 unidades de salida

#input X con OJAs , y sanger

#luego variar la magnitud de A , y peos iniciales

#que pasa si algun A_i es igual al otro A_j

def GeneraA(hasta , desde):

    A = np.arange(hasta , desde , -1)

    return(A.reshape(-1 , A.shape[0]))

A_1 = GeneraA(6 , 0)

def GeneraX(A):

    X = []

    for i in range(0 , len(A)):

        X.append(np.random.uniform((-1*A[i]) , A[i]))

    return(np.array(X).reshape(len(A) , -1))


X_1 = GeneraX(A_1)

print('A_dim: ' , A_1.shape , "\n" , 'A: ' ,  A_1 , "\n" , 'X_dim: ' , X_1.shape , "\n" , 'X: ' , X_1)

A_dim:  (1, 6) 
 A:  [[6 5 4 3 2 1]] 
 X_dim:  (1, 6) 
 X:  [[-4.44809387  4.69315061  3.86264773 -1.21805974  0.54522759 -0.31395049]]


In [ ]:
NoSuperv(X_1)

dataset_dim: (1, 6)
x_dim: (1, 6)
y_dim: (1, 4)
dim_y_k: () dim_w_i_k: () el producto: 0.2883967372032691 * [[ 0.07151683 -0.0938662   0.07892426  0.02415747]
 [ 0.07151683 -0.0938662   0.07892426  0.02415747]]
dim_y_k: () dim_w_i_k: () el producto: 0.9104485767053064 * [[ 0.07151683 -0.0938662   0.07892426  0.02415747]
 [ 0.09594218  0.09320558 -0.0213771   0.02629109]]
dim_y_k: () dim_w_i_k: () el producto: -0.5534042045970353 * [[ 0.07151683 -0.0938662   0.07892426  0.02415747]
 [ 0.07688486 -0.01060151 -0.02035653  0.00268896]]
dim_y_k: () dim_w_i_k: () el producto: 0.14025165570883932 * [[ 0.07151683 -0.0938662   0.07892426  0.02415747]
 [ 0.08322739 -0.09411419  0.04302534 -0.06924579]]
EBE: -0.10512401776319694 y_i_k: 0.2883967372032691 w_i_k: 0.0
dim_y_k: () dim_w_i_k: () el producto: 0.2883967372032691 * [[ 0.09594218  0.09320558 -0.0213771   0.02629109]
 [ 0.07151683 -0.0938662   0.07892426  0.02415747]]
dim_y_k: () dim_w_i_k: () el producto: 0.9104485767053064 * [[ 0.0959421

array([[ 0.07026434, -0.09782025,  0.08132768,  0.02354836],
       [ 0.09725875,  0.09736187, -0.02390345,  0.02693135],
       [ 0.07799187, -0.00710677, -0.02248077,  0.00322732],
       [ 0.08290356, -0.09513649,  0.04364673, -0.06940328],
       [-0.03682139, -0.03541064,  0.0222912 ,  0.09960691],
       [ 0.06103612, -0.00481545, -0.05296044,  0.07855075]])

In [ ]:
#falta hacer la segunda parte de esta guia

array([[ 6.,  8., 10.],
       [ 6.,  8., 10.]])

2

In [ ]:
"""
aca voy a armar las matrices del problema2
"""

(2, 3)

In [ ]:
m1 =np.array([[4,0,0.5],[0,2,0.5]])

m2 = np.array([[1,0.5,3/4],[0.5,1,3/4]])

m3 = np.array([[1,1,1],[0.5,0.5,0.5]])

print(m1 , m2 , m3)

[[4.  0.  0.5]
 [0.  2.  0.5]] [[1.   0.5  0.75]
 [0.5  1.   0.75]] [[1.  1.  1. ]
 [0.5 0.5 0.5]]
